# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dushyant Bansal
tagline:          Dushyant Bansal
url:              http://locahost:4000
paginate:         1
baseurl:          "" 
author:
  name:           Dushyant Bansal
  url:            https://twitter.com/dushyant_db
  email:          dushyant37@gmail.com

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/db42/db42.github.io

pages_list:
  About:		  '/about'	
  Archive:        '/archive'

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
